services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PW}@mongo:27017/
      - POSTGRES_PW=${POSTGRES_PW}
    volumes:
      - .:/app

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
